# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: webdriverio-ci

env: 
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
        - name: Install Chromium
          run: sudo apt-get install chromium-browser
        - uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v1
          with:
            node-version: 16.x
        - name: Install
          run: npm install
        - name: Test
          run: npx wdio wdio.conf.js
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs
